

package dev.mokkery.tests;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.TestMetadata;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.mokkery.tests.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic")
@TestDataPath("$PROJECT_ROOT")
public class MinimumMokkeryDiagnosticTestGenerated extends AbstractMinimumMokkeryDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostic() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("FirDiagnosticsNotReportedWhenDisabled.kt")
  public void testFirDiagnosticsNotReportedWhenDisabled() {
    runTest("test-mokkery-compiler/src/testBase/data/diagnostic/FirDiagnosticsNotReportedWhenDisabled.kt");
  }

  @Nested
  @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/matchers")
  @TestDataPath("$PROJECT_ROOT")
  public class Matchers {
    @Test
    public void testAllFilesPresentInMatchers() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/matchers"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Nested
    @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/declarations")
    @TestDataPath("$PROJECT_ROOT")
    public class Declarations {
      @Test
      public void testAllFilesPresentInDeclarations() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/declarations"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("MatcherArgMatcherParamMustNotBeAnnotatedWithMatcher.kt")
      public void testMatcherArgMatcherParamMustNotBeAnnotatedWithMatcher() {
        runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/declarations/MatcherArgMatcherParamMustNotBeAnnotatedWithMatcher.kt");
      }

      @Test
      @TestMetadata("MatcherMokkeryMatcherScopeParamMustNotBeAnnotatedWithMatcher.kt")
      public void testMatcherMokkeryMatcherScopeParamMustNotBeAnnotatedWithMatcher() {
        runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/declarations/MatcherMokkeryMatcherScopeParamMustNotBeAnnotatedWithMatcher.kt");
      }

      @Test
      @TestMetadata("MatcherMustBeFinal.kt")
      public void testMatcherMustBeFinal() {
        runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/declarations/MatcherMustBeFinal.kt");
      }

      @Test
      @TestMetadata("MatcherMustBeRegularFunction.kt")
      public void testMatcherMustBeRegularFunction() {
        runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/declarations/MatcherMustBeRegularFunction.kt");
      }

      @Test
      @TestMetadata("MatcherMustNotBeFinal.kt")
      public void testMatcherMustNotBeFinal() {
        runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/declarations/MatcherMustNotBeFinal.kt");
      }
    }

    @Nested
    @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage")
    @TestDataPath("$PROJECT_ROOT")
    public class Usage {
      @Test
      public void testAllFilesPresentInUsage() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Nested
      @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder")
      @TestDataPath("$PROJECT_ROOT")
      public class Builder {
        @Test
        public void testAllFilesPresentInBuilder() {
          KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder"), Pattern.compile("^(.+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("MatcherMustNotBeAssignedToOuterScopeVar.kt")
        public void testMatcherMustNotBeAssignedToOuterScopeVar() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder/MatcherMustNotBeAssignedToOuterScopeVar.kt");
        }

        @Test
        @TestMetadata("MatcherMustNotBeAssignedToVariableThatIsNotInitializedWithMatcher.kt")
        public void testMatcherMustNotBeAssignedToVariableThatIsNotInitializedWithMatcher() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder/MatcherMustNotBeAssignedToVariableThatIsNotInitializedWithMatcher.kt");
        }

        @Test
        @TestMetadata("MatcherMustNotBePassedToNonMatcherParams.kt")
        public void testMatcherMustNotBePassedToNonMatcherParams() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder/MatcherMustNotBePassedToNonMatcherParams.kt");
        }

        @Test
        @TestMetadata("MatcherMustNotBeReturnedFromTryCatch.kt")
        public void testMatcherMustNotBeReturnedFromTryCatch() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder/MatcherMustNotBeReturnedFromTryCatch.kt");
        }

        @Test
        @TestMetadata("MatcherMustNotBeUsedAsCondition.kt")
        public void testMatcherMustNotBeUsedAsCondition() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder/MatcherMustNotBeUsedAsCondition.kt");
        }

        @Test
        @TestMetadata("MatcherMustNotBeUsedInNestedClasses.kt")
        public void testMatcherMustNotBeUsedInNestedClasses() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder/MatcherMustNotBeUsedInNestedClasses.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBePassedToMethods.kt")
        public void testMatchersMustNotBePassedToMethods() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder/MatchersMustNotBePassedToMethods.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBePassedToRegularFunctions.kt")
        public void testMatchersMustNotBePassedToRegularFunctions() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder/MatchersMustNotBePassedToRegularFunctions.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedAsWhenSubject.kt")
        public void testMatchersMustNotBeUsedAsWhenSubject() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder/MatchersMustNotBeUsedAsWhenSubject.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedInNestedFunctions.kt")
        public void testMatchersMustNotBeUsedInNestedFunctions() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder/MatchersMustNotBeUsedInNestedFunctions.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedWithOperators.kt")
        public void testMatchersMustNotBeUsedWithOperators() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder/MatchersMustNotBeUsedWithOperators.kt");
        }

        @Test
        @TestMetadata("MatchesMustNotBeUsedWithCompositeMatchers.kt")
        public void testMatchesMustNotBeUsedWithCompositeMatchers() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder/MatchesMustNotBeUsedWithCompositeMatchers.kt");
        }

        @Test
        @TestMetadata("MethodsCannotBeInvokedOnMatchers.kt")
        public void testMethodsCannotBeInvokedOnMatchers() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder/MethodsCannotBeInvokedOnMatchers.kt");
        }

        @Test
        @TestMetadata("TemplatingMustNotBeNested.kt")
        public void testTemplatingMustNotBeNested() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder/TemplatingMustNotBeNested.kt");
        }
      }

      @Nested
      @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating")
      @TestDataPath("$PROJECT_ROOT")
      public class Templating {
        @Test
        public void testAllFilesPresentInTemplating() {
          KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating"), Pattern.compile("^(.+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("MatchersMustNotBeAssignedToOuterScopeVars.kt")
        public void testMatchersMustNotBeAssignedToOuterScopeVars() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/MatchersMustNotBeAssignedToOuterScopeVars.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeAssignedToVariableThatIsNotInitializedWithMatchers.kt")
        public void testMatchersMustNotBeAssignedToVariableThatIsNotInitializedWithMatchers() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/MatchersMustNotBeAssignedToVariableThatIsNotInitializedWithMatchers.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBePassedToNonMatcherParam.kt")
        public void testMatchersMustNotBePassedToNonMatcherParam() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/MatchersMustNotBePassedToNonMatcherParam.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBePassedToRegularFunctions.kt")
        public void testMatchersMustNotBePassedToRegularFunctions() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/MatchersMustNotBePassedToRegularFunctions.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeReturnedFromTryCatch.kt")
        public void testMatchersMustNotBeReturnedFromTryCatch() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/MatchersMustNotBeReturnedFromTryCatch.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedAsConditions.kt")
        public void testMatchersMustNotBeUsedAsConditions() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/MatchersMustNotBeUsedAsConditions.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedAsWhenSubject.kt")
        public void testMatchersMustNotBeUsedAsWhenSubject() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/MatchersMustNotBeUsedAsWhenSubject.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedInNestedClasses.kt")
        public void testMatchersMustNotBeUsedInNestedClasses() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/MatchersMustNotBeUsedInNestedClasses.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedInNestedFunctions.kt")
        public void testMatchersMustNotBeUsedInNestedFunctions() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/MatchersMustNotBeUsedInNestedFunctions.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedWithFinalClasses.kt")
        public void testMatchersMustNotBeUsedWithFinalClasses() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/MatchersMustNotBeUsedWithFinalClasses.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedWithFinalMethods.kt")
        public void testMatchersMustNotBeUsedWithFinalMethods() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/MatchersMustNotBeUsedWithFinalMethods.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedWithMoreThanOneSpreadOperator.kt")
        public void testMatchersMustNotBeUsedWithMoreThanOneSpreadOperator() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/MatchersMustNotBeUsedWithMoreThanOneSpreadOperator.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedWithOperators.kt")
        public void testMatchersMustNotBeUsedWithOperators() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/MatchersMustNotBeUsedWithOperators.kt");
        }

        @Test
        @TestMetadata("MatchesMustNotBeUsedWithCompositeMatchers.kt")
        public void testMatchesMustNotBeUsedWithCompositeMatchers() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/MatchesMustNotBeUsedWithCompositeMatchers.kt");
        }

        @Test
        @TestMetadata("MethodsCannotBeInvokedOnMatchers.kt")
        public void testMethodsCannotBeInvokedOnMatchers() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/MethodsCannotBeInvokedOnMatchers.kt");
        }

        @Test
        @TestMetadata("TemplatingMustNotBeNested.kt")
        public void testTemplatingMustNotBeNested() {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/TemplatingMustNotBeNested.kt");
        }
      }
    }
  }

  @Nested
  @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/mock")
  @TestDataPath("$PROJECT_ROOT")
  public class Mock {
    @Test
    public void testAllFilesPresentInMock() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/mock"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("FinalTypesMustNotBeMocked.kt")
    public void testFinalTypesMustNotBeMocked() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/FinalTypesMustNotBeMocked.kt");
    }

    @Test
    @TestMetadata("IgnoresFinalMembersWhenFlagIgnoreFinalMembersRaised.kt")
    public void testIgnoresFinalMembersWhenFlagIgnoreFinalMembersRaised() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/IgnoresFinalMembersWhenFlagIgnoreFinalMembersRaised.kt");
    }

    @Test
    @TestMetadata("IgnoresInlineMembersWhenIgnoreInlineMembersRaised.kt")
    public void testIgnoresInlineMembersWhenIgnoreInlineMembersRaised() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/IgnoresInlineMembersWhenIgnoreInlineMembersRaised.kt");
    }

    @Test
    @TestMetadata("OverridableTypesWithFinalMembersCannotBeMockeWhenFlagIgnoreInlineMembersRaised.kt")
    public void testOverridableTypesWithFinalMembersCannotBeMockeWhenFlagIgnoreInlineMembersRaised() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/OverridableTypesWithFinalMembersCannotBeMockeWhenFlagIgnoreInlineMembersRaised.kt");
    }

    @Test
    @TestMetadata("OverridableTypesWithFinalMembersCannotBeMocked.kt")
    public void testOverridableTypesWithFinalMembersCannotBeMocked() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/OverridableTypesWithFinalMembersCannotBeMocked.kt");
    }

    @Test
    @TestMetadata("PrimitiveTypesMustNotBeMocked.kt")
    public void testPrimitiveTypesMustNotBeMocked() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/PrimitiveTypesMustNotBeMocked.kt");
    }

    @Test
    @TestMetadata("PrivateConstructorTypesMustNotBeMocked.kt")
    public void testPrivateConstructorTypesMustNotBeMocked() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/PrivateConstructorTypesMustNotBeMocked.kt");
    }

    @Test
    @TestMetadata("SealedTypesMustNotBeMocked.kt")
    public void testSealedTypesMustNotBeMocked() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/SealedTypesMustNotBeMocked.kt");
    }

    @Test
    @TestMetadata("TypeParametersCannotBeUsedWithMockFunctions.kt")
    public void testTypeParametersCannotBeUsedWithMockFunctions() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/TypeParametersCannotBeUsedWithMockFunctions.kt");
    }

    @Nested
    @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/mock/many")
    @TestDataPath("$PROJECT_ROOT")
    public class Many {
      @Test
      public void testAllFilesPresentInMany() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/mock/many"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("MockManyWithGenericTypeDuplicatesCannotBeMocked.kt")
      public void testMockManyWithGenericTypeDuplicatesCannotBeMocked() {
        runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/many/MockManyWithGenericTypeDuplicatesCannotBeMocked.kt");
      }

      @Test
      @TestMetadata("MockManyWithMultipleSuperClassesCannotBeMocked.kt")
      public void testMockManyWithMultipleSuperClassesCannotBeMocked() {
        runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/many/MockManyWithMultipleSuperClassesCannotBeMocked.kt");
      }

      @Test
      @TestMetadata("MockManyWithTypeDuplicatesCannotBeMocked.kt")
      public void testMockManyWithTypeDuplicatesCannotBeMocked() {
        runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/many/MockManyWithTypeDuplicatesCannotBeMocked.kt");
      }
    }

    @Nested
    @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/mock/parameterized")
    @TestDataPath("$PROJECT_ROOT")
    public class Parameterized {
      @Test
      public void testAllFilesPresentInParameterized() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/mock/parameterized"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("ParameterizedConstructorClassWithClassWithoutPublicConstructorCannotBeMocked.kt")
      public void testParameterizedConstructorClassWithClassWithoutPublicConstructorCannotBeMocked() {
        runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/parameterized/ParameterizedConstructorClassWithClassWithoutPublicConstructorCannotBeMocked.kt");
      }

      @Test
      @TestMetadata("ParameterizedConstructorClassWithRecursionCannotBeMocked.kt")
      public void testParameterizedConstructorClassWithRecursionCannotBeMocked() {
        runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/parameterized/ParameterizedConstructorClassWithRecursionCannotBeMocked.kt");
      }

      @Test
      @TestMetadata("ParametrizedConstructorNoConstructorToStubClassInheritenceEnabledCannotBeMocked.kt")
      public void testParametrizedConstructorNoConstructorToStubClassInheritenceEnabledCannotBeMocked() {
        runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/parameterized/ParametrizedConstructorNoConstructorToStubClassInheritenceEnabledCannotBeMocked.kt");
      }

      @Test
      @TestMetadata("ParametrizedConstructorNoConstructorToStubConcreteInstantiationEnabledCannotBeMocked.kt")
      public void testParametrizedConstructorNoConstructorToStubConcreteInstantiationEnabledCannotBeMocked() {
        runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/parameterized/ParametrizedConstructorNoConstructorToStubConcreteInstantiationEnabledCannotBeMocked.kt");
      }
    }
  }

  @Nested
  @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/templating")
  @TestDataPath("$PROJECT_ROOT")
  public class Templating {
    @Test
    public void testAllFilesPresentInTemplating() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/templating"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("FunctionReferenceChainMustNotBePassedToEvery.kt")
    public void testFunctionReferenceChainMustNotBePassedToEvery() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/templating/FunctionReferenceChainMustNotBePassedToEvery.kt");
    }

    @Test
    @TestMetadata("FunctionReferenceIncorrectTypeMustNotBePassedToEvery.kt")
    public void testFunctionReferenceIncorrectTypeMustNotBePassedToEvery() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/templating/FunctionReferenceIncorrectTypeMustNotBePassedToEvery.kt");
    }

    @Test
    @TestMetadata("FunctionReferenceWithoutBoundObjectMustNotBePassedToEvery.kt")
    public void testFunctionReferenceWithoutBoundObjectMustNotBePassedToEvery() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/templating/FunctionReferenceWithoutBoundObjectMustNotBePassedToEvery.kt");
    }

    @Test
    @TestMetadata("MustNotDeclareFunctionsAcceptingMokkeryTemplatingScope.kt")
    public void testMustNotDeclareFunctionsAcceptingMokkeryTemplatingScope() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/templating/MustNotDeclareFunctionsAcceptingMokkeryTemplatingScope.kt");
    }

    @Test
    @TestMetadata("PropertyFunctionReferenceThatIsNotAccessorMustNotBePassedToEvery.kt")
    public void testPropertyFunctionReferenceThatIsNotAccessorMustNotBePassedToEvery() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/templating/PropertyFunctionReferenceThatIsNotAccessorMustNotBePassedToEvery.kt");
    }

    @Test
    @TestMetadata("TemplatingLambdasMustNotBePassedToTemplatingFunctions.kt")
    public void testTemplatingLambdasMustNotBePassedToTemplatingFunctions() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/templating/TemplatingLambdasMustNotBePassedToTemplatingFunctions.kt");
    }

    @Test
    @TestMetadata("ValuePassedToEveryReferenceOverloadMustBeActualReferece.kt")
    public void testValuePassedToEveryReferenceOverloadMustBeActualReferece() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/templating/ValuePassedToEveryReferenceOverloadMustBeActualReferece.kt");
    }
  }
}
