package dev.mokkery.mockable.plugin.ir.transformer

import dev.mokkery.mockable.plugin.ir.MokkeryMockableIr
import dev.mokkery.plugin.core.ir.IrMokkeryPluginScope
import dev.mokkery.plugin.core.ir.irBuiltIns
import dev.mokkery.plugin.core.ir.isMokkeryConstructor
import dev.mokkery.plugin.core.ir.transformer.CoreTransformer
import dev.mokkery.plugin.core.ir.transformer.declarationIrBuilder
import org.jetbrains.kotlin.ir.IrStatement
import org.jetbrains.kotlin.ir.builders.irBlockBody
import org.jetbrains.kotlin.ir.builders.irDelegatingConstructorCall
import org.jetbrains.kotlin.ir.builders.irUnit
import org.jetbrains.kotlin.ir.declarations.IrClass
import org.jetbrains.kotlin.ir.declarations.IrConstructor
import org.jetbrains.kotlin.ir.types.IrType
import org.jetbrains.kotlin.ir.types.classOrFail
import org.jetbrains.kotlin.ir.types.isAny
import org.jetbrains.kotlin.ir.util.constructors
import org.jetbrains.kotlin.ir.util.isInterface
import org.jetbrains.kotlin.ir.util.primaryConstructor

class MokkeryMockableConstructorGenerationTransformer(
    pluginScope: IrMokkeryPluginScope
) : CoreTransformer(pluginScope) {

    override fun visitConstructor(declaration: IrConstructor): IrStatement {
        if (declaration.origin != MokkeryMockableIr.Origin) return declaration
        val cls = declaration.parent as? IrClass ?: return declaration
        val superType = cls.superClassOrAnyType()
        val superConstructor = when {
            superType.isAny() -> superType.classOrFail.owner.primaryConstructor!!
            else -> superType.classOrFail
                .owner
                .constructors
                .find { it.isMokkeryConstructor() }
                ?: error("${superType.classOrFail.owner.name.asString()} does not have a constructor generated by Mokkery!")
        }
        declaration.body = declaration.symbol.declarationIrBuilder {
            irBlockBody {
                +irDelegatingConstructorCall(superConstructor).apply {
                    superConstructor
                        .parameters
                        .forEach { arguments[it] = irUnit() }
                }
            }
        }
        return declaration
    }

    private fun IrClass.superClassOrAnyType(): IrType {
        return superTypes
            .find { !it.isInterface() }
            ?: irBuiltIns.anyType
    }
}
