

package dev.mokkery.tests;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.TestMetadata;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.mokkery.tests.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic")
@TestDataPath("$PROJECT_ROOT")
public class DefaultMokkeryDiagnosticTestGenerated extends AbstractDefaultMokkeryDiagnosticTest {
  private void run(String fileName) {
    runTest("test-mokkery-compiler/src/testBase/data/diagnostic/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDiagnostic() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("FirDiagnosticsNotReportedWhenDisabled.kt")
  public void testFirDiagnosticsNotReportedWhenDisabled() {
    run("FirDiagnosticsNotReportedWhenDisabled.kt");
  }

  @Nested
  @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/matchers")
  @TestDataPath("$PROJECT_ROOT")
  public class Matchers {
    private void run(String fileName) {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/" + fileName);
    }

    @Test
    public void testAllFilesPresentInMatchers() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/matchers"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Nested
    @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/declarations")
    @TestDataPath("$PROJECT_ROOT")
    public class Declarations {
      private void run(String fileName) {
        runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/declarations/" + fileName);
      }

      @Test
      public void testAllFilesPresentInDeclarations() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/declarations"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("MatcherArgMatcherParamMustNotBeAnnotatedWithMatcher.kt")
      public void testMatcherArgMatcherParamMustNotBeAnnotatedWithMatcher() {
        run("MatcherArgMatcherParamMustNotBeAnnotatedWithMatcher.kt");
      }

      @Test
      @TestMetadata("MatcherMokkeryMatcherScopeParamMustNotBeAnnotatedWithMatcher.kt")
      public void testMatcherMokkeryMatcherScopeParamMustNotBeAnnotatedWithMatcher() {
        run("MatcherMokkeryMatcherScopeParamMustNotBeAnnotatedWithMatcher.kt");
      }

      @Test
      @TestMetadata("MatcherMustBeFinal.kt")
      public void testMatcherMustBeFinal() {
        run("MatcherMustBeFinal.kt");
      }

      @Test
      @TestMetadata("MatcherMustBeRegularFunction.kt")
      public void testMatcherMustBeRegularFunction() {
        run("MatcherMustBeRegularFunction.kt");
      }

      @Test
      @TestMetadata("MatcherMustNotBeFinal.kt")
      public void testMatcherMustNotBeFinal() {
        run("MatcherMustNotBeFinal.kt");
      }
    }

    @Nested
    @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage")
    @TestDataPath("$PROJECT_ROOT")
    public class Usage {
      private void run(String fileName) {
        runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/" + fileName);
      }

      @Test
      public void testAllFilesPresentInUsage() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Nested
      @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder")
      @TestDataPath("$PROJECT_ROOT")
      public class Builder {
        private void run(String fileName) {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder/" + fileName);
        }

        @Test
        public void testAllFilesPresentInBuilder() {
          KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/builder"), Pattern.compile("^(.+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("MatcherMustNotBeAssignedToOuterScopeVar.kt")
        public void testMatcherMustNotBeAssignedToOuterScopeVar() {
          run("MatcherMustNotBeAssignedToOuterScopeVar.kt");
        }

        @Test
        @TestMetadata("MatcherMustNotBeAssignedToVariableThatIsNotInitializedWithMatcher.kt")
        public void testMatcherMustNotBeAssignedToVariableThatIsNotInitializedWithMatcher() {
          run("MatcherMustNotBeAssignedToVariableThatIsNotInitializedWithMatcher.kt");
        }

        @Test
        @TestMetadata("MatcherMustNotBePassedToNonMatcherParams.kt")
        public void testMatcherMustNotBePassedToNonMatcherParams() {
          run("MatcherMustNotBePassedToNonMatcherParams.kt");
        }

        @Test
        @TestMetadata("MatcherMustNotBeReturnedFromTryCatch.kt")
        public void testMatcherMustNotBeReturnedFromTryCatch() {
          run("MatcherMustNotBeReturnedFromTryCatch.kt");
        }

        @Test
        @TestMetadata("MatcherMustNotBeUsedAsCondition.kt")
        public void testMatcherMustNotBeUsedAsCondition() {
          run("MatcherMustNotBeUsedAsCondition.kt");
        }

        @Test
        @TestMetadata("MatcherMustNotBeUsedInNestedClasses.kt")
        public void testMatcherMustNotBeUsedInNestedClasses() {
          run("MatcherMustNotBeUsedInNestedClasses.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBePassedToMethods.kt")
        public void testMatchersMustNotBePassedToMethods() {
          run("MatchersMustNotBePassedToMethods.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBePassedToRegularFunctions.kt")
        public void testMatchersMustNotBePassedToRegularFunctions() {
          run("MatchersMustNotBePassedToRegularFunctions.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedAsWhenSubject.kt")
        public void testMatchersMustNotBeUsedAsWhenSubject() {
          run("MatchersMustNotBeUsedAsWhenSubject.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedInNestedFunctions.kt")
        public void testMatchersMustNotBeUsedInNestedFunctions() {
          run("MatchersMustNotBeUsedInNestedFunctions.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedWithOperators.kt")
        public void testMatchersMustNotBeUsedWithOperators() {
          run("MatchersMustNotBeUsedWithOperators.kt");
        }

        @Test
        @TestMetadata("MatchesMustNotBeUsedWithCompositeMatchers.kt")
        public void testMatchesMustNotBeUsedWithCompositeMatchers() {
          run("MatchesMustNotBeUsedWithCompositeMatchers.kt");
        }

        @Test
        @TestMetadata("MethodsCannotBeInvokedOnMatchers.kt")
        public void testMethodsCannotBeInvokedOnMatchers() {
          run("MethodsCannotBeInvokedOnMatchers.kt");
        }

        @Test
        @TestMetadata("TemplatingMustNotBeNested.kt")
        public void testTemplatingMustNotBeNested() {
          run("TemplatingMustNotBeNested.kt");
        }
      }

      @Nested
      @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating")
      @TestDataPath("$PROJECT_ROOT")
      public class Templating {
        private void run(String fileName) {
          runTest("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating/" + fileName);
        }

        @Test
        public void testAllFilesPresentInTemplating() {
          KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/matchers/usage/templating"), Pattern.compile("^(.+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("MatchersMustNotBeAssignedToOuterScopeVars.kt")
        public void testMatchersMustNotBeAssignedToOuterScopeVars() {
          run("MatchersMustNotBeAssignedToOuterScopeVars.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeAssignedToVariableThatIsNotInitializedWithMatchers.kt")
        public void testMatchersMustNotBeAssignedToVariableThatIsNotInitializedWithMatchers() {
          run("MatchersMustNotBeAssignedToVariableThatIsNotInitializedWithMatchers.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBePassedToNonMatcherParam.kt")
        public void testMatchersMustNotBePassedToNonMatcherParam() {
          run("MatchersMustNotBePassedToNonMatcherParam.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBePassedToRegularFunctions.kt")
        public void testMatchersMustNotBePassedToRegularFunctions() {
          run("MatchersMustNotBePassedToRegularFunctions.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeReturnedFromTryCatch.kt")
        public void testMatchersMustNotBeReturnedFromTryCatch() {
          run("MatchersMustNotBeReturnedFromTryCatch.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedAsConditions.kt")
        public void testMatchersMustNotBeUsedAsConditions() {
          run("MatchersMustNotBeUsedAsConditions.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedAsWhenSubject.kt")
        public void testMatchersMustNotBeUsedAsWhenSubject() {
          run("MatchersMustNotBeUsedAsWhenSubject.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedInNestedClasses.kt")
        public void testMatchersMustNotBeUsedInNestedClasses() {
          run("MatchersMustNotBeUsedInNestedClasses.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedInNestedFunctions.kt")
        public void testMatchersMustNotBeUsedInNestedFunctions() {
          run("MatchersMustNotBeUsedInNestedFunctions.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedWithFinalClasses.kt")
        public void testMatchersMustNotBeUsedWithFinalClasses() {
          run("MatchersMustNotBeUsedWithFinalClasses.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedWithFinalMethods.kt")
        public void testMatchersMustNotBeUsedWithFinalMethods() {
          run("MatchersMustNotBeUsedWithFinalMethods.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedWithMoreThanOneSpreadOperator.kt")
        public void testMatchersMustNotBeUsedWithMoreThanOneSpreadOperator() {
          run("MatchersMustNotBeUsedWithMoreThanOneSpreadOperator.kt");
        }

        @Test
        @TestMetadata("MatchersMustNotBeUsedWithOperators.kt")
        public void testMatchersMustNotBeUsedWithOperators() {
          run("MatchersMustNotBeUsedWithOperators.kt");
        }

        @Test
        @TestMetadata("MatchesMustNotBeUsedWithCompositeMatchers.kt")
        public void testMatchesMustNotBeUsedWithCompositeMatchers() {
          run("MatchesMustNotBeUsedWithCompositeMatchers.kt");
        }

        @Test
        @TestMetadata("MethodsCannotBeInvokedOnMatchers.kt")
        public void testMethodsCannotBeInvokedOnMatchers() {
          run("MethodsCannotBeInvokedOnMatchers.kt");
        }

        @Test
        @TestMetadata("TemplatingMustNotBeNested.kt")
        public void testTemplatingMustNotBeNested() {
          run("TemplatingMustNotBeNested.kt");
        }
      }
    }
  }

  @Nested
  @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/mock")
  @TestDataPath("$PROJECT_ROOT")
  public class Mock {
    private void run(String fileName) {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/" + fileName);
    }

    @Test
    public void testAllFilesPresentInMock() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/mock"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("AllowMockableAnnotatedToBeMocked.kt")
    public void testAllowMockableAnnotatedToBeMocked() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/AllowMockableAnnotatedToBeMocked.kt");
    }

    @Test
    @TestMetadata("FinalTypesMustNotBeMocked.kt")
    public void testFinalTypesMustNotBeMocked() {
      run("FinalTypesMustNotBeMocked.kt");
    }

    @Test
    @TestMetadata("IgnoresFinalMembersWhenFlagIgnoreFinalMembersRaised.kt")
    public void testIgnoresFinalMembersWhenFlagIgnoreFinalMembersRaised() {
      run("IgnoresFinalMembersWhenFlagIgnoreFinalMembersRaised.kt");
    }

    @Test
    @TestMetadata("IgnoresInlineMembersWhenIgnoreInlineMembersRaised.kt")
    public void testIgnoresInlineMembersWhenIgnoreInlineMembersRaised() {
      run("IgnoresInlineMembersWhenIgnoreInlineMembersRaised.kt");
    }

    @Test
    @TestMetadata("OverridableTypesWithFinalMembersCannotBeMockeWhenFlagIgnoreInlineMembersRaised.kt")
    public void testOverridableTypesWithFinalMembersCannotBeMockeWhenFlagIgnoreInlineMembersRaised() {
      run("OverridableTypesWithFinalMembersCannotBeMockeWhenFlagIgnoreInlineMembersRaised.kt");
    }

    @Test
    @TestMetadata("OverridableTypesWithFinalMembersCannotBeMocked.kt")
    public void testOverridableTypesWithFinalMembersCannotBeMocked() {
      run("OverridableTypesWithFinalMembersCannotBeMocked.kt");
    }

    @Test
    @TestMetadata("PrimitiveTypesMustNotBeMocked.kt")
    public void testPrimitiveTypesMustNotBeMocked() {
      run("PrimitiveTypesMustNotBeMocked.kt");
    }

    @Test
    @TestMetadata("PrivateConstructorTypesMustNotBeMocked.kt")
    public void testPrivateConstructorTypesMustNotBeMocked() {
      run("PrivateConstructorTypesMustNotBeMocked.kt");
    }

    @Test
    @TestMetadata("SealedTypesMustNotBeMocked.kt")
    public void testSealedTypesMustNotBeMocked() {
      run("SealedTypesMustNotBeMocked.kt");
    }

    @Test
    @TestMetadata("TypeParametersCannotBeUsedWithMockFunctions.kt")
    public void testTypeParametersCannotBeUsedWithMockFunctions() {
      run("TypeParametersCannotBeUsedWithMockFunctions.kt");
    }

    @Nested
    @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/mock/many")
    @TestDataPath("$PROJECT_ROOT")
    public class Many {
      private void run(String fileName) {
        runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/many/" + fileName);
      }

      @Test
      public void testAllFilesPresentInMany() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/mock/many"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("MockManyWithGenericTypeDuplicatesCannotBeMocked.kt")
      public void testMockManyWithGenericTypeDuplicatesCannotBeMocked() {
        run("MockManyWithGenericTypeDuplicatesCannotBeMocked.kt");
      }

      @Test
      @TestMetadata("MockManyWithMultipleSuperClassesCannotBeMocked.kt")
      public void testMockManyWithMultipleSuperClassesCannotBeMocked() {
        run("MockManyWithMultipleSuperClassesCannotBeMocked.kt");
      }

      @Test
      @TestMetadata("MockManyWithTypeDuplicatesCannotBeMocked.kt")
      public void testMockManyWithTypeDuplicatesCannotBeMocked() {
        run("MockManyWithTypeDuplicatesCannotBeMocked.kt");
      }
    }

    @Nested
    @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/mock/parameterized")
    @TestDataPath("$PROJECT_ROOT")
    public class Parameterized {
      private void run(String fileName) {
        runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mock/parameterized/" + fileName);
      }

      @Test
      public void testAllFilesPresentInParameterized() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/mock/parameterized"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("ParameterizedConstructorClassWithClassWithoutPublicConstructorCannotBeMocked.kt")
      public void testParameterizedConstructorClassWithClassWithoutPublicConstructorCannotBeMocked() {
        run("ParameterizedConstructorClassWithClassWithoutPublicConstructorCannotBeMocked.kt");
      }

      @Test
      @TestMetadata("ParameterizedConstructorClassWithRecursionCannotBeMocked.kt")
      public void testParameterizedConstructorClassWithRecursionCannotBeMocked() {
        run("ParameterizedConstructorClassWithRecursionCannotBeMocked.kt");
      }

      @Test
      @TestMetadata("ParametrizedConstructorNoConstructorToStubClassInheritenceEnabledCannotBeMocked.kt")
      public void testParametrizedConstructorNoConstructorToStubClassInheritenceEnabledCannotBeMocked() {
        run("ParametrizedConstructorNoConstructorToStubClassInheritenceEnabledCannotBeMocked.kt");
      }

      @Test
      @TestMetadata("ParametrizedConstructorNoConstructorToStubConcreteInstantiationEnabledCannotBeMocked.kt")
      public void testParametrizedConstructorNoConstructorToStubConcreteInstantiationEnabledCannotBeMocked() {
        run("ParametrizedConstructorNoConstructorToStubConcreteInstantiationEnabledCannotBeMocked.kt");
      }
    }
  }

  @Nested
  @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/mockable")
  @TestDataPath("$PROJECT_ROOT")
  public class Mockable {
    @Test
    public void testAllFilesPresentInMockable() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/mockable"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("AllowStubbingMockableWithoutPermission.kt")
    public void testAllowStubbingMockableWithoutPermission() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mockable/AllowStubbingMockableWithoutPermission.kt");
    }

    @Test
    @TestMetadata("FirDiagnosticsNotReportedWhenDisabled.kt")
    public void testFirDiagnosticsNotReportedWhenDisabled() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mockable/FirDiagnosticsNotReportedWhenDisabled.kt");
    }

    @Test
    @TestMetadata("InnerClassCannotBeMockable.kt")
    public void testInnerClassCannotBeMockable() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mockable/InnerClassCannotBeMockable.kt");
    }

    @Test
    @TestMetadata("LocalClassCannotBeMockable.kt")
    public void testLocalClassCannotBeMockable() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mockable/LocalClassCannotBeMockable.kt");
    }

    @Test
    @TestMetadata("SuperClassMustBeMockable.kt")
    public void testSuperClassMustBeMockable() {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/mockable/SuperClassMustBeMockable.kt");
    }
  }

  @Nested
  @TestMetadata("test-mokkery-compiler/src/testBase/data/diagnostic/templating")
  @TestDataPath("$PROJECT_ROOT")
  public class Templating {
    private void run(String fileName) {
      runTest("test-mokkery-compiler/src/testBase/data/diagnostic/templating/" + fileName);
    }

    @Test
    public void testAllFilesPresentInTemplating() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("test-mokkery-compiler/src/testBase/data/diagnostic/templating"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("FunctionReferenceChainMustNotBePassedToEvery.kt")
    public void testFunctionReferenceChainMustNotBePassedToEvery() {
      run("FunctionReferenceChainMustNotBePassedToEvery.kt");
    }

    @Test
    @TestMetadata("FunctionReferenceIncorrectTypeMustNotBePassedToEvery.kt")
    public void testFunctionReferenceIncorrectTypeMustNotBePassedToEvery() {
      run("FunctionReferenceIncorrectTypeMustNotBePassedToEvery.kt");
    }

    @Test
    @TestMetadata("FunctionReferenceWithoutBoundObjectMustNotBePassedToEvery.kt")
    public void testFunctionReferenceWithoutBoundObjectMustNotBePassedToEvery() {
      run("FunctionReferenceWithoutBoundObjectMustNotBePassedToEvery.kt");
    }

    @Test
    @TestMetadata("MustNotDeclareFunctionsAcceptingMokkeryTemplatingScope.kt")
    public void testMustNotDeclareFunctionsAcceptingMokkeryTemplatingScope() {
      run("MustNotDeclareFunctionsAcceptingMokkeryTemplatingScope.kt");
    }

    @Test
    @TestMetadata("PropertyFunctionReferenceThatIsNotAccessorMustNotBePassedToEvery.kt")
    public void testPropertyFunctionReferenceThatIsNotAccessorMustNotBePassedToEvery() {
      run("PropertyFunctionReferenceThatIsNotAccessorMustNotBePassedToEvery.kt");
    }

    @Test
    @TestMetadata("TemplatingLambdasMustNotBePassedToTemplatingFunctions.kt")
    public void testTemplatingLambdasMustNotBePassedToTemplatingFunctions() {
      run("TemplatingLambdasMustNotBePassedToTemplatingFunctions.kt");
    }

    @Test
    @TestMetadata("ValuePassedToEveryReferenceOverloadMustBeActualReferece.kt")
    public void testValuePassedToEveryReferenceOverloadMustBeActualReferece() {
      run("ValuePassedToEveryReferenceOverloadMustBeActualReferece.kt");
    }
  }
}
